-- supabase/migrations/xxxxxxxxxx_initial_schema.sql (例)
-- スレッドテーブル
CREATE TABLE public.threads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name TEXT NOT NULL,
    content TEXT NOT NULL,
    ip_address INET NOT NULL,
    is_hidden BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
ALTER TABLE public.threads ADD CONSTRAINT threads_pkey PRIMARY KEY (id);

-- コメントテーブル
CREATE TABLE public.comments (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    thread_id BIGINT NOT NULL,
    parent_id UUID,
    user_name TEXT NOT NULL,
    comment_text TEXT NOT NULL,
    ip_address INET NOT NULL,
    hierarchy_level INTEGER NOT NULL,
    is_hidden BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
ALTER TABLE public.comments ADD CONSTRAINT comments_pkey PRIMARY KEY (id);
ALTER TABLE public.comments ADD CONSTRAINT comments_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.threads(id) ON DELETE CASCADE;
ALTER TABLE public.comments ADD CONSTRAINT comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.comments(id) ON DELETE CASCADE;

-- RLS有効化 (全てのテーブルで必要)
ALTER TABLE public.threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- RLSポリシー (Threads)
CREATE POLICY "Public threads are viewable by everyone." ON public.threads FOR SELECT USING (is_hidden = FALSE);
CREATE POLICY "Public users can create threads." ON public.threads FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins can update threads." ON public.threads FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can delete/hide threads." ON public.threads FOR DELETE USING (auth.role() = 'authenticated');

-- RLSポリシー (Comments)
CREATE POLICY "Public comments are viewable by everyone." ON public.comments FOR SELECT USING (is_hidden = FALSE);
CREATE POLICY "Public users can create comments." ON public.comments FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins can update comments." ON public.comments FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can delete/hide comments." ON public.comments FOR DELETE USING (auth.role() = 'authenticated');